# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import MLEvalService_pb2 as MLEvalService__pb2


class MLEvalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.unary_unary(
                '/tlib.svc.mleval_svc.MLEvalService/Evaluate',
                request_serializer=MLEvalService__pb2.MLEval.SerializeToString,
                response_deserializer=MLEvalService__pb2.Outcome.FromString,
                )


class MLEvalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLEvalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=MLEvalService__pb2.MLEval.FromString,
                    response_serializer=MLEvalService__pb2.Outcome.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tlib.svc.mleval_svc.MLEvalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MLEvalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tlib.svc.mleval_svc.MLEvalService/Evaluate',
            MLEvalService__pb2.MLEval.SerializeToString,
            MLEvalService__pb2.Outcome.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
