# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MLEvalService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13MLEvalService.proto\x12\x13tlib.svc.mleval_svc\"-\n\x04\x44\x61ta\x12\x12\n\ndata_value\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\"G\n\tInputData\x12\x11\n\tdata_path\x18\x01 \x01(\t\x12\'\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x19.tlib.svc.mleval_svc.Data\"K\n\x06MLEval\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12-\n\x05input\x18\x02 \x01(\x0b\x32\x1e.tlib.svc.mleval_svc.InputData\"2\n\x07Outcome\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2X\n\rMLEvalService\x12G\n\x08\x45valuate\x12\x1b.tlib.svc.mleval_svc.MLEval\x1a\x1c.tlib.svc.mleval_svc.Outcome\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MLEvalService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATA']._serialized_start=44
  _globals['_DATA']._serialized_end=89
  _globals['_INPUTDATA']._serialized_start=91
  _globals['_INPUTDATA']._serialized_end=162
  _globals['_MLEVAL']._serialized_start=164
  _globals['_MLEVAL']._serialized_end=239
  _globals['_OUTCOME']._serialized_start=241
  _globals['_OUTCOME']._serialized_end=291
  _globals['_MLEVALSERVICE']._serialized_start=293
  _globals['_MLEVALSERVICE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
